spring:
  jpa:
    hibernate:
      ddl-auto: create-drop
      generate-ddl: false
  h2:
    console:
      enabled: true
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:testdb;DB_CLOSE_DELAY=-1
    username: sa
    password:
  flyway:
    enabled: false